#+TITLE: A Few Poems
#+DATE: [2018-09-29 Sat 10:29]
#+AUTHOR: Narendra Joshi

A few poems that I have written are here: [[http://narendraj9.blogspot.in][Words Paper and Life]]


* Nostalgia
  :PROPERTIES:
  :CUSTOM_ID: nostalgia
  :END:

Another day sinks and disappears,\\
The slate gets a few more strokes.\\
I think and wonder, an unending craving,\\
Looking at the far-away mountains,\\
Draped in snowy mist at a tempting distance--\\
/Where would my heart find a better home?/

Like a childish belief in talks to a God,\\
The presence of a bigger truth turns a myth everyday.\\
Maybe there is no God in the bigger things,\\
No wonders that only an eagle's eye would see.\\
Maybe life is lived in little pieces only\\
Of bursts of laughter or pangs of pain,\\
Of silence-filled walks or smile-worn days.\\
Maybe that's all there is to it.\\
And maybe everything else just sets the backdrop\\
Or I would wake up and smile one day\\
Reading this page. Remembering this day.


* Departure
  :PROPERTIES:
  :CUSTOM_ID: departure
  :END:

Sails of my little boat flapping to the tunes of traveling winds,\\
As I leave the realm of the known to walk with shaky feet again,\\
Play a symphony that only aches my heart even more.\\
I see in the distance, faces new. In the distance, faces old.\\
There is heaviness in my heart for sure.\\
And the chills can still reach my bones, silent and cold.\\
But I walk this wire. I will be someone else again.\\
Like all stories, written on oceanic tides,\\
Mine would become a part of the shore, placid and earthed. [Sedimentary
Rock :-D]


* A Lovely Day
  :PROPERTIES:
  :CUSTOM_ID: a-lovely-day
  :END:

A clearer sky emblazoned with such beautifying cloudiness\\
Roofs restlessness and more than a few endless chases.\\
Within life's confused web, a resting plateau;\\
Only plateaus, no peaks, I have learned.\\
Another day would etch wrinkles on the face of time,\\
Caresses on a wrinkled face, with wrinkled hands,\\
My mind's box has it's own definition of beauty, it seems.\\
I wonder and smile, I look look outside, close my eyes.\\
The air is fresher, silence pleasant for a change.\\
Today seems like one of those lovely days.


* Whims
  :PROPERTIES:
  :CUSTOM_ID: whims
  :END:

If I had wings, or the magic of a sorcerer's wand,\\
Or the swiftness of my wandering thoughts,\\
Or the strength of the never tiring winds,\\
I would be there before you fall asleep tonight\\
And let you know how in my mind, I caress your cheeks\\
And what the word and signs, they all mean.

What I feel isn't the shallow whim of a wandering mind\\
Which on time's call would fall into pieces\\
But the steady calmness of a mind in rest\\
Amid the million chases of these worldly worries.\\
You are my resting stone, the silence and the song.\\
But my love I am human, weak and strong, so are you.\\
I need you close and I need your hands\\
To hold me, to touch, to feel and see.\\
How your eyes twinkle when they meet mine,\\
Or how your lips taste in these chilly winters\\
Or how your brows curl in a smile\\
On the little foolishness your sweetest slave plays.\\
But I don't want them now, and now\\
Neither in the 'near' future if it means\\
Saying no to my love for distance's sake\\
When it can be, when it can be...\\
Truer a little farther in time.

So, my love I love, these gaps of silence and sleep\\
Of the dormant and the dancing wishes of time\\
Waiting to feel your lips on mine\\
And my hands playing with those twines of hair.\\
I will be there. Or I will take you here.\\
Or we will have a world of a different attire\\
Until my love, you say it's best\\
And finally, you lay beside me under the covers\\
And these blankets forget the smell of loneliness.


* A Lost Poem
  :PROPERTIES:
  :CUSTOM_ID: a-lost-poem
  :END:

Places bathe in sunshine and shade.\\
Structures gigantic, with time, decay.\\
Beauty and colors fade, to my dismay.\\
Each moment at its own pace\\
Marches to the beats of an oldened drum. (let's name it "time")

Waves oceanic, they retreat\\
After, with the shore, having a meet.\\
Faces of the moon, shadowy afternoons,\\
Songs of Silence, the vigor of vengeance,\\
Fruits of a tree, the hum of a bee;\\
With Time all fall into laps of change, you know.\\
Amid these changes, I can assure\\
My Love would stand brave and bold.\\
As time would etch age on my face\\
And weakness would crawl into my days,\\
My hand would lay held out for you,\\
My Love, I promise, agelessly true.\\
My Raison D'etre! You are\\
In my days and in my dreams;\\
For none would be complete without thee\\
Stay with me Stay with me.


* Eyes
  :PROPERTIES:
  :CUSTOM_ID: eyes
  :END:

Eyes, those eyes, they say. They speak\\
A language so foreign to me--\\
A thousand words in a single blink;\\
A song that I have been chasing.\\
When they smile, curved the brows;\\
Resembling pearls embedded in snow,\\
All the seven wanderers, I know,\\
Envy our little dusty globe!\\
In bitter times, the twins they dive\\
Into majestic oceans and seas.\\
Ruby red, shiny wet\\
Silencing every word meant to hurt.\\
All my world of words won't suffice\\
To be just with those two eyes.\\
Audio:
[[https://drive.google.com/open?id=0Bw3s0KNkAWLINnU3SFNzUlk2UUE][Recitation]]


* Nostalgia
  :PROPERTIES:
  :CUSTOM_ID: nostalgia-1
  :END:

Amid a thousand passing seconds\\
None of which dearer to the Gods,\\
It's so strange of this human heart\\
That only a few it adores.\\
It could be her eyes;\\
Could be some six year old's smile;\\
Could be rainbows in the sky\\
Or an equation after those years of time;\\
Could be the sunshine\\
Or that ball of snow that lovingly hit your face.\\
Could be the water, cold and sweet and tastless at the same time.\\
Or the fire that lets you read through darkness;\\
It could be silence, void and complete and strange\\
Or cheerful voices shouting at the top of their lungs.\\
Could be just words, ink and paper and life\\
Or the canvas you paint every night,\\
Or be forgotten and remembered those dreams.\\
But do those blind and deaf moments know\\
How much of your life they have made?


* Seclusion
  :PROPERTIES:
  :CUSTOM_ID: seclusion
  :END:

A tryst, Of the silence and a few fleeting thoughts;\\
Leaves a constellation of eerie knots.\\
Am I a slave to the passing time\\
Or the winds, not chariot mine?\\
Stillness has answers that refuse;\\
Maybe it is the seclusion, still and calm\\
Or these words just smudge those lines.


* Love
  :PROPERTIES:
  :CUSTOM_ID: love
  :END:

Hunger timely fills my cage;\\
Pain embraces me before the breakage;\\
Restlessness finds me on a lonelier day;\\
In silence, in chaos, in peace or in a war;\\
My hands are never nearer never farther away.\\
Why then love needs your presence today?

Your eyes, shinier and still-- yet not so --\\
Lay their warmth upon my face;\\
Your lips can sing to my heart's content\\
Or march my soul to its death bed.\\
Why my love, my love isn't love\\
Until only you feel its feathers?

Sleep engulfs me after days exhaust my pace;\\
Worlds wander distressed in the endless chase;\\
Of silence and peace; In distress and disease.\\
I am I in all of the chaos, my mind mine, not lost so\\
For these mountains are its own, the rivers it has flown;\\
Yet your presence softens its edge; tamed with a kiss\\
And a gaze silences the curious; turns to prayers and a wish.\\
What have you if not some beyond love\\
That all the love within me isn't enough?
* A Constellation of Thoughts
  :PROPERTIES:
  :CUSTOM_ID: a-constellation-of-thoughts
  :END:

Looking at the starry sky tonight, I wonder\\
How many worlds unknown to me, blossom and die.\\
The silence, accompanied by the whisper of drunken winds\\
Engulfs me with the same emotion I had in a crowded place\\
Where my worlds weren't the twinkling spots on the blue muslin\\
But faces in a hurry, faces painted with worries.\\
Someone was on a run, someone else had the headphones on.\\
One lost in glitter of passing days, the other in music\\
That only lends one the numbness of thoughts.\\
Someone smiled, secretly with a machine he owned,\\
Someone else I saw was too young to understand\\
But it seemed as if he was a lot wiser than me\\
Unknown to things he can't change, worlds he can't gauge.

With all this complexity, unfathomable whose depth,\\
Of the lives that live within me, of the ones with me,\\
It's a strange force that leads us through our days.\\
An eagle's eye might see the chaos of my world\\
But my world isn't his. His worlds will never be mine.\\
It's only in vague terms one can say\\
About things that one finds hard to explain.\\
Maybe it's the short length of my voyage so far\\
Or maybe it is the bodily boundaries of the cage I wear.\\
Or maybe I am left to adore in awe the creations of the Master\\
Until the call that puts it to an end.


* From the light of Polaris
  :PROPERTIES:
  :CUSTOM_ID: from-the-light-of-polaris
  :END:

No new morrow would see me abandon your streets\\
For I have lived there longer than I have lived.\\
There may be no road ahead, only the endless sea\\
With a lonesome traveler laying desirous stares\\
On the setting Sun, as if it would rise in her world\\
To have his message be reached, and felt.\\
It may make no sense to the keepers of wisdom\\
But I've never declared my being as wise\\
For it has always been the foolish things\\
That turned passing time to memories\\
And the feet of the wise is shaky and meek\\
When they say it's faith, and wisdom fleets.

No fears dwell these valleys I walk.\\
Fearful are those with walls raised,\\
Of wanting, or of loss;\\
I have treasures that no one can steal\\
And I hope you still believe in them.

This may never become a poem\\
But then neither those that I have ever written are.\\
Unlike those ramblings from all corners of my heart,\\
Each word here holds a meaning, I assure\\
For it's hard to say what I mean\\
When it's not what you want.

I remember more than I thought I would\\
Of the time we lived and the worlds we crafted.\\
The last page of an old notebook still holds a little petal\\
Dearer to me than all roses I have ever seen.\\
I remember your eyes, when we met after days a few\\
And how they were filled with an emotion I don't have a word for;\\
The corners of my wandering mind still meet the traveler once I was\\
Sometimes the walls bring smiles, sometimes a few regrets you know.

Smile, at least for once for all this world of words\\
Stays in the realm of worthlessness\\
Unless you let your lips curl as your mind reads\\
And your eyes speak as if a young lover kissed them;\\
Shyly blinking with a shimmer of heavens\\
That's all I am wishing for. That's all this is for.


* An Evening
  :PROPERTIES:
  :CUSTOM_ID: an-evening
  :END:

If you let me, I will be the wind to caress your face\\
When the morning light shines with your hair.\\
I will be the loving wetness on your cheeks\\
Subliming and dissolving at the same time.\\
I will be the silence that soothes your forehead\\
With every line struggling to leave a mark;\\
I will be the boredom of your days\\
And the chaos of your celebrations.\\
I will write my heart out on every stone you step upon\\
And still be left with a million words to say.\\
I will be the one you will want on every knock on the door\\
And the smile that adores your face when it's known.


* A Happy Day
  :PROPERTIES:
  :CUSTOM_ID: a-happy-day
  :END:

My laces to traveling shoes, yes, laces.\\
I remember, Do I?, the song of the wind\\
As we listened to the ticks from our pasts\\
And dreamed of waves at our shore in the distance.

My flickering lights on a full-moon sky, yes, those lights.\\
I still feel, Don't I do?, the woken up hair on my skin\\
As I dived into your eyes, on a chilly morning bus ride\\
And I hope I have told you happiness is when they shine.

My magic to a mundane day, yes magic, you know.\\
Like a broken poem, a hopeless aim, a senseless song, secluded fame.\\
Yes, magic.\\
Yes, it's you! :)
